name: omuse-ci

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-omuse-ci
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        python-version: ['3.8']

    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.os }}-Python${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4
      with:
        # Need to correctly generate version number using setuptools_scm
        # See: https://github.com/pypa/setuptools_scm/issues/480
        fetch-depth: 0
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install libopenmpi-dev

    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install openmpi || true
        ln -s /usr/local/bin/gfortran-13 /usr/local/bin/gfortran

    - name: Install python dependencies
      run: |
        pip install --upgrade pip setuptools wheel setuptools_scm amuse-framework

    - name: Install development
      run: |
        pip install -e .
